name: Build and Release WinForms App

on:
  push:
    branches:
      - master # Trigger on push to main branch
    tags:
      - 'v*' # Trigger on tags starting with 'v'

permissions:
  contents: write   # Required to create releases

jobs:
  build:
    runs-on: windows-latest   # IMPORTANT for WinForms

    steps:
      - name: Checkout Repository # Checkout the code
        uses: actions/checkout@v4 # Checkout the repository

      - name: Setup .NET 10 SDK # Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4 
        with:
          dotnet-version: 10.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Publish Portable Build
        run: |
          dotnet publish ./MusicPlayerProject/MusicPlayerProject.csproj `
          -c Release `
            -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -o publish

      - name: Create ZIP
        run: Compress-Archive -Path publish\* -DestinationPath MysticalMusicApp-${{ github.ref_name }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: MysticalMusicApp-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}