name: Build and Release WinForms App

on:
  push:
    branches:
      - master # Trigger on push to main branch
    tags:
      - 'v*' # Trigger on tags starting with 'v'

permissions:
  contents: write   # Required to create releases

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: dotnet restore

      - name: Publish
        run: |
          msbuild ./MusicPlayer.csproj `
            /p:Configuration=Release `
            /p:RuntimeIdentifier=win-x64 `
            /p:SelfContained=true `
            /p:PublishSingleFile=true `
            /p:IncludeNativeLibrariesForSelfExtract=true `
            /p:PublishDir=publish\

      - name: Zip
        run: Compress-Archive -Path publish\* -DestinationPath MusicPlayer-${{ github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: MusicPlayer-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}